select ID,
BOROUGH,
NEIGHBORHOOD ||', '|| BOROUGH as LOCATION,
SCHOOL_NAME,
NEIGHBORHOOD,
INTEREST,
METHOD,
ATTENDANCE_RATE,
GRADUATION_RATE,
SCHOOL_SPORTS,
TOTAL_STUDENTS,
to_char(TOTAL_STUDENTS,'999G999G999G999G999') as total_students_disp,
SAFE
from HIGHSCHOOLS
