drop table img_categoria cascade constraints;
drop table img_documento cascade constraints;
-- create tables

create table img_categoria (
    id            number generated by default on null as identity
                  constraint img_categoria_id_pk primary key,
    categoria     varchar2(30 char) not null,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);



create table img_documento (
    id                   number generated by default on null as identity
                         constraint img_documento_id_pk primary key,
    categoria_id         number                         constraint img_documento_categoria_id_fk
                         references img_categoria,
    titolo               varchar2(50 char) not null,
    descrizione          varchar2(4096 char) not null,
    data                 date not null,
    immagine             blob,
    immagine_filename    varchar2(255 char),
    immagine_mimetype    varchar2(255 char),
    immagine_charset     varchar2(255 char),
    immagine_lastupd     date,
    created              date not null,
    created_by           varchar2(255 char) not null,
    updated              date not null,
    updated_by           varchar2(255 char) not null
);

-- table index
create index img_documento_i1 on img_documento (categoria_id);



-- triggers
create or replace trigger img_categoria_biu
    before insert or update
    on img_categoria
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end img_categoria_biu;
/


create or replace trigger img_documento_biu
    before insert or update
    on img_documento
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end img_documento_biu;
/


-- Generated by Quick SQL 1.2.9 26/03/2026, 11:13:49

/*
categoria
  categoria vc30 /nn


documento
  titolo vc50 /nn
  descrizione vc4k /nn
  data d /nn
  immagine file
  categoria_id



 Non-default options:
# settings = {"apex":"Y","auditcols":true,"db":"23","drop":true,"prefix":"img","pk":"IDENTITY"}

*/
